name: coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install go-acc for coverage
        run: |
          go install github.com/ory/go-acc@v0.2.6

      - name: Run tests with coverage
        run: |
          go-acc -o coverage.txt ./... -- -v --race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
