name: Test CICD
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_CICD_jobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Today = $(date + %y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello, World!, today is ${{ env.Today }}